import dotenv from "dotenv";
import express from "express";
import cors from "cors";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { ObjectId } from "mongodb";

dotenv.config({ path: "atlas-credentials.env" });
const { connectToMongoDB, checkMongoDBConnection } = await import("../db/mongodb.mjs");
const app=express(),port=Number(process.env.PORT||5000),jwtSecret=process.env.JWT_SECRET||"spacesync-local-development-change-me";
const origins=(process.env.CLIENT_URL||"http://localhost:3000,http://localhost:5173").split(",").map(x=>x.trim());
const ROLE_PERMISSIONS={
 super_admin:["dashboard:view","resources:view","resources:manage","bookings:view_all","bookings:manage","approvals:manage","analytics:view","users:manage","profile:manage"],
 space_admin:["dashboard:view","resources:view","resources:manage","bookings:view_all","bookings:manage","approvals:manage","analytics:view","profile:manage"],
 member:["dashboard:view","resources:view","bookings:create","bookings:view_own","bookings:cancel_own","profile:manage"]
};
app.use(cors({origin:origins,credentials:true}));app.use(express.json({limit:"100kb"}));
const emailOf=v=>String(v||"").trim().toLowerCase();
const permissionsFor=role=>ROLE_PERMISSIONS[role]||ROLE_PERMISSIONS.member;
const publicUser=u=>({id:String(u._id),name:u.name,email:u.email,role:u.role,organization:u.organization,phone:u.phone||"",jobTitle:u.jobTitle||"",permissions:permissionsFor(u.role)});
const tokenFor=u=>jwt.sign({sub:String(u._id),email:u.email,role:u.role,organization:u.organization},jwtSecret,{expiresIn:"7d",issuer:"spacesync-api",audience:"spacesync-web"});
function auth(req,res,next){try{const h=req.headers.authorization||"";req.auth=jwt.verify(h.startsWith("Bearer ")?h.slice(7):"",jwtSecret,{issuer:"spacesync-api",audience:"spacesync-web"});next()}catch{res.status(401).json({message:"Your session is invalid or has expired."})}}
const permit=permission=>(req,res,next)=>permissionsFor(req.auth.role).includes(permission)?next():res.status(403).json({message:"You do not have permission to perform this action."});
const oid=value=>{try{return new ObjectId(value)}catch{return null}};
const sameOrg=(req,value)=>value===req.auth.organization;

app.get("/api/health",async(_req,res)=>{try{const r=await checkMongoDBConnection();res.json({status:"ok",database:r.database})}catch{res.status(503).json({status:"error",message:"Database unavailable."})}});
app.post("/api/auth/register",async(req,res)=>{
 const name=String(req.body.name||"").trim(),email=emailOf(req.body.email),password=String(req.body.password||""),organization=String(req.body.organization||"").trim();
 if(name.length<2||!email.includes("@")||password.length<8||organization.length<2)return res.status(400).json({message:"Enter a valid name, organization, email, and password of at least 8 characters."});
 try{const db=await connectToMongoDB(),users=db.collection("users");await users.createIndex({email:1},{unique:true});if(await users.findOne({email}))return res.status(409).json({message:"An account already exists for this email."});const now=new Date(),user={name,email,passwordHash:await bcrypt.hash(password,12),organization,role:"member",status:"active",createdAt:now,updatedAt:now,lastLoginAt:now};const result=await users.insertOne(user);user._id=result.insertedId;res.status(201).json({token:tokenFor(user),user:publicUser(user)})}catch(e){res.status(e?.code===11000?409:500).json({message:e?.code===11000?"An account already exists for this email.":"Account creation failed."})}
});
app.post("/api/auth/login",async(req,res)=>{try{const db=await connectToMongoDB(),users=db.collection("users"),login=emailOf(req.body.email),user=await users.findOne({$or:[{email:login},{username:login}]});if(!user||!(await bcrypt.compare(String(req.body.password||""),user.passwordHash)))return res.status(401).json({message:"Username/email or password is incorrect."});if(user.status!=="active")return res.status(403).json({message:"This account is disabled."});await users.updateOne({_id:user._id},{$set:{lastLoginAt:new Date()}});res.json({token:tokenFor(user),user:publicUser(user)})}catch{res.status(500).json({message:"Login is temporarily unavailable."})}});
app.get("/api/auth/me",auth,async(req,res)=>{const db=await connectToMongoDB(),user=await db.collection("users").findOne({_id:oid(req.auth.sub),status:"active"});if(!user)return res.status(404).json({message:"Account not found."});res.json({user:publicUser(user)})});
app.post("/api/auth/forgot-password",async(req,res)=>{const email=emailOf(req.body.email);if(email.includes("@")){const db=await connectToMongoDB();await db.collection("passwordResetRequests").insertOne({email,status:"pending",requestedAt:new Date(),expiresAt:new Date(Date.now()+1800000)})}res.json({message:"If an account exists, recovery instructions will be sent."})});

app.get("/api/dashboard",auth,async(req,res)=>{const db=await connectToMongoDB(),org=req.auth.organization,userId=oid(req.auth.sub),now=new Date(),end=new Date(Date.now()+30*86400000);const bookingFilter=req.auth.role==="member"?{organization:org,createdBy:userId}:{organization:org};const [resources,bookings,users,pending]=await Promise.all([db.collection("resources").countDocuments({organization:org,status:{$ne:"archived"}}),db.collection("bookings").countDocuments({...bookingFilter,startAt:{$gte:now,$lte:end},status:{$ne:"cancelled"}}),db.collection("users").countDocuments({organization:org,status:"active"}),db.collection("bookings").countDocuments({organization:org,status:"pending"})]);res.json({stats:{resources,bookings,users,pending}})});
app.get("/api/resources",auth,permit("resources:view"),async(req,res)=>{const db=await connectToMongoDB();const items=await db.collection("resources").find({organization:req.auth.organization,status:{$ne:"archived"}}).sort({name:1}).toArray();res.json({resources:items.map(x=>({...x,id:String(x._id),_id:undefined}))})});
app.post("/api/resources",auth,permit("resources:manage"),async(req,res)=>{const name=String(req.body.name||"").trim(),type=String(req.body.type||"Room").trim(),location=String(req.body.location||"").trim(),capacity=Number(req.body.capacity||1);if(!name||!location||capacity<1)return res.status(400).json({message:"Name, location, and capacity are required."});const db=await connectToMongoDB(),item={name,type,location,capacity,amenities:Array.isArray(req.body.amenities)?req.body.amenities:[],requiresApproval:Boolean(req.body.requiresApproval),status:"available",organization:req.auth.organization,createdBy:oid(req.auth.sub),createdAt:new Date()};const r=await db.collection("resources").insertOne(item);res.status(201).json({resource:{...item,id:String(r.insertedId)}})});
app.get("/api/bookings",auth,async(req,res)=>{const db=await connectToMongoDB(),filter={organization:req.auth.organization};if(req.auth.role==="member")filter.createdBy=oid(req.auth.sub);const items=await db.collection("bookings").find(filter).sort({startAt:1}).limit(250).toArray();res.json({bookings:items.map(x=>({...x,id:String(x._id),resourceId:String(x.resourceId),createdBy:String(x.createdBy),_id:undefined}))})});
app.post("/api/bookings",auth,permit("bookings:create"),async(req,res)=>{const db=await connectToMongoDB(),resourceId=oid(req.body.resourceId),startAt=new Date(req.body.startAt),endAt=new Date(req.body.endAt),title=String(req.body.title||"").trim();if(!resourceId||!title||isNaN(startAt)||isNaN(endAt)||endAt<=startAt)return res.status(400).json({message:"Valid booking details are required."});const resource=await db.collection("resources").findOne({_id:resourceId,organization:req.auth.organization,status:{$ne:"archived"}});if(!resource)return res.status(404).json({message:"Resource not found."});const conflict=await db.collection("bookings").findOne({resourceId,status:{$in:["confirmed","pending"]},startAt:{$lt:endAt},endAt:{$gt:startAt}});if(conflict)return res.status(409).json({message:"This resource is already booked during that time."});const item={title,resourceId,resourceName:resource.name,startAt,endAt,attendees:Number(req.body.attendees||1),notes:String(req.body.notes||""),organization:req.auth.organization,createdBy:oid(req.auth.sub),createdByName:req.body.createdByName||req.auth.email,status:resource.requiresApproval?"pending":"confirmed",createdAt:new Date()};const r=await db.collection("bookings").insertOne(item);res.status(201).json({booking:{...item,id:String(r.insertedId)}})});
app.patch("/api/bookings/:id/status",auth,permit("bookings:manage"),async(req,res)=>{const status=String(req.body.status||"");if(!["confirmed","denied","cancelled","completed"].includes(status))return res.status(400).json({message:"Invalid booking status."});const db=await connectToMongoDB(),result=await db.collection("bookings").updateOne({_id:oid(req.params.id),organization:req.auth.organization},{$set:{status,reviewedBy:oid(req.auth.sub),reviewedAt:new Date()}});res.status(result.matchedCount?200:404).json(result.matchedCount?{message:"Booking updated."}:{message:"Booking not found."})});
app.delete("/api/bookings/:id",auth,async(req,res)=>{const db=await connectToMongoDB(),filter={_id:oid(req.params.id),organization:req.auth.organization};if(req.auth.role==="member")filter.createdBy=oid(req.auth.sub);const result=await db.collection("bookings").updateOne(filter,{$set:{status:"cancelled",cancelledAt:new Date()}});res.status(result.matchedCount?200:404).json(result.matchedCount?{message:"Booking cancelled."}:{message:"Booking not found."})});
app.get("/api/users",auth,permit("users:manage"),async(req,res)=>{const db=await connectToMongoDB(),items=await db.collection("users").find({organization:req.auth.organization},{projection:{passwordHash:0}}).sort({name:1}).toArray();res.json({users:items.map(publicUser)})});
app.patch("/api/profile",auth,permit("profile:manage"),async(req,res)=>{const name=String(req.body.name||"").trim(),phone=String(req.body.phone||"").trim(),jobTitle=String(req.body.jobTitle||"").trim();if(name.length<2)return res.status(400).json({message:"A valid name is required."});const db=await connectToMongoDB();await db.collection("users").updateOne({_id:oid(req.auth.sub)},{$set:{name,phone,jobTitle,updatedAt:new Date()}});const user=await db.collection("users").findOne({_id:oid(req.auth.sub)});res.json({user:publicUser(user)})});
app.use((_req,res)=>res.status(404).json({message:"Endpoint not found."}));
app.listen(port,async()=>{try{await checkMongoDBConnection();console.log(`SpaceSync API ready on http://localhost:${port}`)}catch(e){console.error(`MongoDB unavailable: ${e.message}`)}});
