"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AuthUser } from "../services/authService";
import { addBooking, addResource, Booking, cancelBooking, getBookings, getDashboard, getResources, getUsers, Resource, setBookingStatus, updateProfile } from "../services/dataService";

const ALL_NAV=[["Overview","OV"],["Calendar","CA"],["My bookings","MB"],["Resources","RS"],["Approvals","AP"],["Analytics","AN"],["Team & access","TM"],["Profile","PF"]] as const;
const roleLabel=(role:string)=>role==="super_admin"?"Super Admin":role==="space_admin"?"Space Admin":"Member";
const fmt=(value:string)=>new Intl.DateTimeFormat("en-PK",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));

function Empty({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <div className="empty-state"><span>SS</span><h3>{title}</h3><p>{copy}</p>{action}</div>}
function Spinner(){return <div className="page-loader"><i/><span>Loading workspace data...</span></div>}

export default function BookingDashboard({currentUser,onLogout}:{currentUser:AuthUser;onLogout:()=>void}){
 const[user,setUser]=useState(currentUser),[active,setActive]=useState("Overview"),[menu,setMenu]=useState(false),[account,setAccount]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[toast,setToast]=useState(""),[bookingOpen,setBookingOpen]=useState(false),[resourceOpen,setResourceOpen]=useState(false);
 const[resources,setResources]=useState<Resource[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[users,setUsers]=useState<AuthUser[]>([]),[stats,setStats]=useState({resources:0,bookings:0,users:0,pending:0});
 const can=(p:string)=>user.permissions?.includes(p);
 const nav=ALL_NAV.filter(([label])=>{
  if(label==="My bookings")return user.role==="member";
  if(label==="Team & access")return can("users:manage");
  if(label==="Approvals")return can("approvals:manage");
  if(label==="Analytics")return can("analytics:view");
  return true;
 });
 async function refresh(){setLoading(true);setError("");try{const[d,r,b]=await Promise.all([getDashboard(),getResources(),getBookings()]);setStats(d.stats);setResources(r.resources);setBookings(b.bookings);if(can("users:manage"))setUsers((await getUsers()).users)}catch(e){setError(e instanceof Error?e.message:"Unable to load workspace.")}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]);
 function notify(v:string){setToast(v);window.setTimeout(()=>setToast(""),3200)}
 const pending=bookings.filter(x=>x.status==="pending"),upcoming=bookings.filter(x=>new Date(x.startAt)>new Date()&&x.status!=="cancelled"),initials=user.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();
 async function createBooking(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await addBooking({title:f.get("title"),resourceId:f.get("resourceId"),startAt:new Date(String(f.get("startAt"))).toISOString(),endAt:new Date(String(f.get("endAt"))).toISOString(),attendees:Number(f.get("attendees")),notes:f.get("notes"),createdByName:user.name});setBookingOpen(false);notify("Booking created successfully.");await refresh()}catch(x){notify(x instanceof Error?x.message:"Booking failed.")}}
 async function createResource(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await addResource({name:String(f.get("name")),type:String(f.get("type")),location:String(f.get("location")),capacity:Number(f.get("capacity")),amenities:String(f.get("amenities")||"").split(",").map(x=>x.trim()).filter(Boolean),requiresApproval:f.get("requiresApproval")==="on"});setResourceOpen(false);notify("Resource added.");await refresh()}catch(x){notify(x instanceof Error?x.message:"Resource creation failed.")}}
 async function updateStatus(id:string,status:string){try{await setBookingStatus(id,status);notify(`Booking ${status}.`);await refresh()}catch(x){notify(x instanceof Error?x.message:"Update failed.")}}
 return <main className="app">
  <aside className={`sidebar ${menu?"open":""}`}><div className="side-head"><div className="brand"><span className="brand-mark"><i/><i/><i/></span><span>SpaceSync<small>Resource operations</small></span></div><button onClick={()=>setMenu(false)}>Close</button></div><div className="org"><span>{user.organization.slice(0,2).toUpperCase()}</span><p><b>{user.organization}</b><small>MongoDB workspace</small></p></div><nav><p>Workspace</p>{nav.map(([label,icon])=><button key={label} className={active===label?"active":""} onClick={()=>{setActive(label);setMenu(false)}}><span>{icon}</span>{label}{label==="Approvals"&&stats.pending>0&&<b>{stats.pending}</b>}</button>)}</nav><div className="side-card"><strong>{stats.resources}</strong><span>Live resources</span><p>All values shown here come from your MongoDB database.</p><button onClick={refresh}>Refresh data</button></div><button className="profile" onClick={()=>setAccount(!account)}><span>{initials}</span><p><b>{user.name}</b><small>{roleLabel(user.role)}</small></p><i>•••</i></button>{account&&<div className="profile-menu"><button onClick={()=>{setActive("Profile");setAccount(false)}}>View profile</button><button onClick={onLogout}>Sign out</button></div>}</aside>
  <section className="main"><header className="header"><button className="menu" onClick={()=>setMenu(true)}>Menu</button><label className="search"><span>Search</span><input placeholder="Search your workspace"/><kbd>Ctrl K</kbd></label><div className="header-actions"><div className="signed-user"><span>{initials}</span><p><b>{user.name}</b><small>{roleLabel(user.role)}</small></p></div>{can("bookings:create")&&<button className="primary" onClick={()=>setBookingOpen(true)}>+ New booking</button>}</div></header>
  {loading?<Spinner/>:error?<div className="load-error"><h2>Couldn’t load SpaceSync</h2><p>{error}</p><button className="primary" onClick={refresh}>Try again</button></div>:<>
   {active==="Overview"&&<Overview user={user} stats={stats} upcoming={upcoming} resources={resources} canBook={can("bookings:create")} book={()=>setBookingOpen(true)} go={setActive}/>}
   {active==="Calendar"&&<Calendar bookings={bookings}/>}
   {active==="My bookings"&&<Bookings title="My bookings" copy="Your reservations from MongoDB." rows={bookings} cancel={async id=>{await cancelBooking(id);notify("Booking cancelled.");refresh()}}/>}
   {active==="Resources"&&<Resources rows={resources} manage={can("resources:manage")} canBook={can("bookings:create")} add={()=>setResourceOpen(true)} book={()=>setBookingOpen(true)}/>}
   {active==="Approvals"&&<Bookings title="Approval queue" copy="Restricted-resource bookings waiting for a decision." rows={pending} approve={updateStatus}/>}
   {active==="Analytics"&&<Analytics stats={stats} bookings={bookings} resources={resources}/>}
   {active==="Team & access"&&<Team users={users}/>}
   {active==="Profile"&&<Profile user={user} save={async input=>{const r=await updateProfile(input);setUser(r.user);notify("Profile updated.")}} logout={onLogout}/>}
  </>}</section>
  {menu&&<button className="overlay" onClick={()=>setMenu(false)}/>}
  {bookingOpen&&<BookingModal resources={resources} close={()=>setBookingOpen(false)} submit={createBooking}/>}
  {resourceOpen&&<ResourceModal close={()=>setResourceOpen(false)} submit={createResource}/>}
  {toast&&<div className="toast"><span>OK</span>{toast}</div>}
 </main>
}

function Overview({user,stats,upcoming,resources,canBook,book,go}:{user:AuthUser;stats:any;upcoming:Booking[];resources:Resource[];canBook:boolean;book:()=>void;go:(v:string)=>void}){return <><section className="hero real-hero"><div><p>LIVE WORKSPACE • {user.organization}</p><h1>Welcome back,<br/><span>{user.name.split(" ")[0]}.</span></h1><h2>Your dashboard is powered by live MongoDB records. Administrators monitor operations while Members reserve resources.</h2><div>{canBook&&<button onClick={book}>Book a resource</button>}<button className={!canBook?"hero-first":""} onClick={()=>go("Calendar")}>Open calendar</button></div><footer><span><b>{stats.resources}</b> resources</span><i/><span><b>{stats.bookings}</b> upcoming</span><i/><span><b>{stats.pending}</b> pending</span></footer></div><aside><div className="visual-calendar"><header><b>Database status</b><span>Live</span></header><article><b>Resources</b><i className="mint a"/></article><article><b>Bookings</b><i className="blue b"/></article><article><b>Members</b><i className="amber c"/></article></div><div className="util"><span>{stats.users}</span><p><b>Active users</b><small>Organization members</small></p></div></aside></section><main className="overview"><div className="metrics"><Metric label="Resources" value={stats.resources}/><Metric label="Upcoming bookings" value={stats.bookings}/><Metric label="Members" value={stats.users}/><Metric label="Pending approval" value={stats.pending}/></div><div className="overview-grid"><section className="panel"><div className="panel-head"><div><p>Real schedule</p><h2>Upcoming bookings</h2></div><button onClick={()=>go(canBook?"My bookings":"Calendar")}>View all</button></div>{upcoming.length?upcoming.slice(0,5).map(x=><article className="live-row" key={x.id}><p><b>{x.title}</b><small>{x.resourceName} • {fmt(x.startAt)}</small></p><em>{x.status}</em></article>):<Empty title="No bookings yet" copy={canBook?"Create your first booking to populate the schedule.":"Member bookings will appear here for monitoring."} action={canBook?<button className="primary" onClick={book}>New booking</button>:undefined}/>}</section><section className="panel"><div className="panel-head"><div><p>MongoDB inventory</p><h2>Resources</h2></div><button onClick={()=>go("Resources")}>View all</button></div>{resources.length?resources.slice(0,5).map(x=><article className="live-row" key={x.id}><p><b>{x.name}</b><small>{x.location} • {x.capacity} people</small></p><em>{x.status}</em></article>):<Empty title="No resources" copy="A Space Admin can add the first room or asset."/>}</section></div></main></>}
function Metric({label,value}:{label:string;value:number}){return <article className="metric"><span className="tone-1">{label.slice(0,2).toUpperCase()}</span><p><small>{label}</small><strong>{value}</strong><i>Live data</i></p></article>}
function Calendar({bookings}:{bookings:Booking[]}){const groups=useMemo(()=>bookings.reduce((a,x)=>{const d=new Date(x.startAt).toDateString();(a[d]??=[]).push(x);return a},{} as Record<string,Booking[]>),[bookings]);return <div className="page"><Title kicker="Live availability" title="Calendar" copy="All confirmed and pending database bookings."/><section className="panel calendar-list">{Object.keys(groups).length?Object.entries(groups).map(([day,items])=><div className="calendar-day" key={day}><h3>{day}</h3>{items.map(x=><article key={x.id}><span>{new Date(x.startAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span><p><b>{x.title}</b><small>{x.resourceName} • {x.createdByName}</small></p><em>{x.status}</em></article>)}</div>):<Empty title="Calendar is empty" copy="Bookings will appear here after they are created."/>}</section></div>}
function Bookings({title,copy,rows,cancel,approve}:{title:string;copy:string;rows:Booking[];cancel?:(id:string)=>void;approve?:(id:string,status:string)=>void}){return <div className="page"><Title kicker="Database records" title={title} copy={copy}/><section className="panel data-table simple-table"><div className="table-head"><span>Booking</span><span>Resource</span><span>Schedule</span><span>Status</span><span>Action</span></div>{rows.length?rows.map(x=><article key={x.id}><span className="row-icon tone-2">BK</span><b>{x.title}</b><span>{x.resourceName}</span><span>{fmt(x.startAt)}</span><em>{x.status}</em><div>{approve?<><button onClick={()=>approve(x.id,"denied")}>Deny</button><button className="approve" onClick={()=>approve(x.id,"confirmed")}>Approve</button></>:x.status!=="cancelled"&&<button onClick={()=>cancel?.(x.id)}>Cancel</button>}</div></article>):<Empty title="No records found" copy="There is no matching MongoDB data yet."/>}</section></div>}
function Resources({rows,manage,canBook,add,book}:{rows:Resource[];manage:boolean;canBook:boolean;add:()=>void;book:()=>void}){return <div className="page"><Title kicker="Live inventory" title="Resources" copy="Rooms, equipment, labs, and spaces stored in MongoDB." action={manage?<button className="primary" onClick={add}>+ Add resource</button>:undefined}/><div className="resource-live-grid">{rows.length?rows.map(x=><article className="resource-live" key={x.id}><span>{x.name.slice(0,2).toUpperCase()}</span><div><small>{x.type}</small><h3>{x.name}</h3><p>{x.location} • {x.capacity} people</p><footer>{x.amenities?.map(a=><i key={a}>{a}</i>)}</footer></div><b>{x.requiresApproval?"Approval required":"Available"}</b>{canBook&&<button onClick={book}>Book</button>}</article>):<Empty title="No resources configured" copy={manage?"Add the first genuine workspace resource.":"Ask a Space Admin to add resources."} action={manage?<button className="primary" onClick={add}>Add resource</button>:undefined}/>}</div></div>}
function Analytics({stats,bookings,resources}:{stats:any;bookings:Booking[];resources:Resource[]}){const confirmed=bookings.filter(x=>x.status==="confirmed").length;return <div className="page"><Title kicker="Real workspace data" title="Analytics" copy="Calculated from current MongoDB records only."/><div className="feature-metrics"><Metric label="Resources" value={stats.resources}/><Metric label="Bookings" value={stats.bookings}/><Metric label="Confirmed" value={confirmed}/></div><section className="panel"><Empty title={bookings.length?"Analytics are active":"Not enough activity yet"} copy={bookings.length?`${bookings.length} bookings across ${resources.length} resources are being tracked.`:"Create bookings to generate utilization and demand analytics."}/></section></div>}
function Team({users}:{users:AuthUser[]}){return <div className="page"><Title kicker="Role-based access" title="Team & access" copy="Genuine registered accounts in this organization."/><section className="panel data-table simple-table">{users.length?users.map(u=><article key={u.id}><span className="row-icon tone-1">{u.name.slice(0,2).toUpperCase()}</span><b>{u.name}</b><span>{u.email}</span><span>{u.organization}</span><em>{roleLabel(u.role)}</em><div><button>Active</button></div></article>):<Empty title="No team members" copy="Registered members will appear here."/>}</section></div>}
function Profile({user,save,logout}:{user:AuthUser;save:(x:{name:string;phone:string;jobTitle:string})=>Promise<void>;logout:()=>void}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save({name:String(f.get("name")),phone:String(f.get("phone")),jobTitle:String(f.get("jobTitle"))})}return <div className="page"><Title kicker="Your account" title="Profile" copy="Manage personal details and review your assigned access."/><div className="profile-layout"><form className="panel profile-form" onSubmit={submit}><div className="profile-hero"><span>{user.name.slice(0,2).toUpperCase()}</span><div><h2>{user.name}</h2><p>{user.email}</p><em>{roleLabel(user.role)}</em></div></div><label><span>Full name</span><input name="name" defaultValue={user.name} required/></label><label><span>Job title</span><input name="jobTitle" defaultValue={user.jobTitle||""} placeholder="e.g. Product Designer"/></label><label><span>Phone</span><input name="phone" defaultValue={user.phone||""} placeholder="+92 300 0000000"/></label><footer><button type="button" onClick={logout}>Sign out</button><button className="primary">Save profile</button></footer></form><section className="panel permission-card"><h2>Access permissions</h2><p>Your role controls what is visible and editable.</p>{user.permissions.map(p=><span key={p}>✓ {p.replaceAll("_"," ").replace(":"," — ")}</span>)}</section></div></div>}
function Title({kicker,title,copy,action}:{kicker:string;title:string;copy:string;action?:React.ReactNode}){return <div className="page-title"><div><p>{kicker}</p><h1>{title}</h1><span>{copy}</span></div>{action}</div>}
function BookingModal({resources,close,submit}:{resources:Resource[];close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-bg" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p>MongoDB booking</p><h2>New booking</h2></div><button onClick={close}>Close</button></div><form onSubmit={submit}><label><span>Title</span><input name="title" required placeholder="Team planning session"/></label><label><span>Resource</span><select name="resourceId" required><option value="">Select a resource</option>{resources.map(x=><option value={x.id} key={x.id}>{x.name} — {x.location}</option>)}</select></label><div className="form-row"><label><span>Starts</span><input name="startAt" type="datetime-local" required/></label><label><span>Ends</span><input name="endAt" type="datetime-local" required/></label></div><label><span>Attendees</span><input name="attendees" type="number" min="1" defaultValue="1"/></label><label><span>Notes</span><input name="notes" placeholder="Optional agenda"/></label><footer><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={!resources.length}>Create booking</button></footer></form></section></div>}
function ResourceModal({close,submit}:{close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-bg" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p>Admin action</p><h2>Add resource</h2></div><button onClick={close}>Close</button></div><form onSubmit={submit}><label><span>Name</span><input name="name" required placeholder="Atlas Room"/></label><div className="form-row"><label><span>Type</span><select name="type"><option>Meeting room</option><option>Lab</option><option>Equipment</option><option>Parking</option></select></label><label><span>Capacity</span><input name="capacity" type="number" min="1" defaultValue="4"/></label></div><label><span>Location</span><input name="location" required placeholder="North Wing, Level 2"/></label><label><span>Amenities</span><input name="amenities" placeholder="Display, Whiteboard, Video"/></label><label className="check-line"><input name="requiresApproval" type="checkbox"/><span>Require admin approval</span></label><footer><button type="button" onClick={close}>Cancel</button><button className="primary">Save resource</button></footer></form></section></div>}
